spring:
  application:
    name: AuthService-migration
  datasource:
    url: jdbc:mysql://localhost:3306/pro_be_auth
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
server:
  port: 8090